version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: "none"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "nuix-topic:1:2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper
    logging:
      driver: "none"
  web:
    build: .
    ports:
      - "5000:5000"