swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /flags: 
    get:
      operationId: "flags.read"
      tags:
        - "Flags"
      summary: "The flag data structure supported by the server application"
      description: "Read the list of flags"
      responses:
        200:
          description: "Successful read flag list operation"
          schema:
            type: "array"
            items:
              properties:
                flag:
                  type: "string"
                message:
                  type: "string"